/**
 * Copy del chrome del informe compartido de Insights (TASK-1875; es-CL, tuteo). Lo editorial —afirmaciones, límites,
 * metodología, etiquetas de métricas— viene escrito en el modelo y NUNCA se reescribe acá.
 */
export const INSIGHTS_COPY = {
  skipLink: 'Saltar al contenido',
  brandEyebrow: 'Lectura de Efeonce',
  preparedFor: 'Preparado para',
  period: 'Período',
  edition: 'Edición',
  editionValue: (code: string, version: number) => `${code} · versión ${version}`,
  asOf: 'Datos al',
  scopeTitle: 'Qué mide este informe',
  periodPartial: 'Período abierto: la fuente aún no cerró este período.',
  periodPartialDetail: 'Las cifras son las del corte indicado y no se actualizan solas.',
  indexTitle: 'Contenido',
  indexToggle: 'Contenido del informe',
  indexSections: (count: number) => `${count} secciones`,
  progressLabel: (current: number, total: number) => `Sección ${current} de ${total}`,
  summaryTitle: 'Resumen ejecutivo',
  essentialsTitle: 'Lo esencial del mes',
  decisionTitle: 'Para decidir en la reunión',
  decisionFooter: 'Recomendación de Efeonce',
  chapterEyebrow: (index: number) => `Capítulo ${String(index).padStart(2, '0')}`,
  moduleLabel: { seo: 'SEO', aeo: 'Respuestas de IA', ico: 'Entrega creativa' } as Record<string, string>,
  meaningTitle: 'Lo que significa',
  nextStepTitle: 'Próximo paso',
  tableShow: 'Ver tabla equivalente',
  tableHide: 'Ocultar tabla equivalente',
  chartBaseline: 'Barras con origen en cero.',
  chartTableOnly: 'Esta figura se lee en su tabla equivalente.',
  provenanceUnit: 'Unidad',
  provenanceSource: 'Fuente',
  observed: 'Medido',
  estimated: 'Estimado',
  absent: 'Sin dato',
  absentReason: 'La fuente no entrega este dato para el período.',
  limitsTitle: 'Límites de este capítulo',
  chapterEmpty: 'Este capítulo no tiene cifras en esta edición.',
  planTitle: 'Plan de acción',
  planLead: 'Cada acción apunta a una métrica que se leerá en el próximo informe.',
  actionsTitle: 'Acciones',
  methodologyTitle: 'Metodología y referencias',
  methodologyHeading: 'De dónde sale cada cifra',
  editionLimits: 'Límites de la edición',
  references: 'Referencias',
  downloadsTitle: 'Descargas',
  downloadLabel: { report_pdf: 'Informe completo', deck_pdf: 'Presentación', web: 'Versión web' } as Record<string, string>,
  downloadFormat: { report_pdf: 'PDF A4', deck_pdf: 'PDF 16:9', web: '' } as Record<string, string>,
  downloadCta: 'Descargar PDF',
  downloadUnavailable: 'No disponible en esta edición',
  linkNotice: 'Este enlace es personal y puede revocarse.',
  linkExpires: (date: string) => `Vence el ${date}.`,
  confidential: (org: string, code: string, version: number) =>
    `Efeonce Group SpA · Documento confidencial para uso exclusivo de ${org} · Edición ${code}, versión ${version}.`,
  states: {
    not_found: { eyebrow: 'Enlace no encontrado', title: 'Este enlace no existe o expiró.', body: 'Pide un enlace nuevo a quien te lo compartió.' },
    gone: { eyebrow: 'Informe retirado', title: 'Este informe fue retirado.', body: 'Si necesitas una versión vigente, pídela a tu contacto en Efeonce.' },
    rate_limited: { eyebrow: 'Demasiadas lecturas', title: 'Demasiadas lecturas en poco tiempo.', body: 'Intenta de nuevo en unos minutos.' },
    error: { eyebrow: 'No pudimos cargarlo', title: 'No pudimos cargar el informe.', body: 'Intenta de nuevo en unos minutos.' },
  },
  contactCta: 'Escribir a Efeonce',
  // Dirección A — tablero de respuestas
  linkActive: 'Enlace vigente',
  expiresShort: (date: string) => `vence el ${date}`,
  dataAsOf: (date: string) => `datos al ${date}`,
  filterAll: 'Todo',
  filterPlan: 'Plan',
  filtersLabel: 'Filtrar el informe por módulo',
  findingsTitle: 'Lo esencial del mes',
  findingsLead: 'Toca un hallazgo para ver su evidencia.',
  findingOpen: 'Ver evidencia',
  findingClose: 'Cerrar',
  copyLink: 'Copiar enlace',
  copyFindingLink: 'Copiar enlace a este hallazgo',
  linkCopied: 'Enlace copiado',
  viewChart: 'Gráfico',
  viewTable: 'Tabla',
  viewSwitch: 'Cambiar entre gráfico y tabla',
  noEvidenceChart: 'Este hallazgo no tiene una figura propia en esta edición.',
  sceneEyebrow: (module: string) => module,
  howMeasured: 'Cómo se midió',
  howMeasuredLead: 'Fuentes, cortes y límites de cada cifra.',
  downloadShort: 'Descargar',
  backToTop: 'Volver arriba',
} as const
