/**
 * Copy del chrome del informe compartido de Insights (TASK-1875). Lo editorial —afirmaciones, límites, metodología,
 * etiquetas de métricas— viene escrito en el modelo y NUNCA se reescribe acá.
 *
 * Dos diccionarios con la misma forma: es-CL (tuteo, el de siempre) y en-US. La página elige por `model.locale` y
 * pasa el diccionario a cada componente, así una edición en inglés no queda con los botones en español.
 */
export const INSIGHTS_COPY = {
  skipLink: 'Saltar al contenido',
  brandEyebrow: 'Lectura de Efeonce',
  preparedFor: 'Preparado para',
  period: 'Período',
  edition: 'Edición',
  editionValue: (code: string, version: number) => `${code} · versión ${version}`,
  asOf: 'Datos al',
  scopeTitle: 'Qué mide este informe',
  periodPartial: 'Período abierto: la fuente aún no cerró este período.',
  periodPartialDetail: 'Las cifras son las del corte indicado y no se actualizan solas.',
  indexTitle: 'Contenido',
  indexToggle: 'Contenido del informe',
  indexSections: (count: number) => `${count} secciones`,
  progressLabel: (current: number, total: number) => `Sección ${current} de ${total}`,
  summaryTitle: 'Resumen ejecutivo',
  essentialsTitle: 'Lo esencial del mes',
  decisionTitle: 'Para decidir en la reunión',
  decisionFooter: 'Recomendación de Efeonce',
  chapterEyebrow: (index: number) => `Capítulo ${String(index).padStart(2, '0')}`,
  meaningTitle: 'Lo que significa',
  nextStepTitle: 'Próximo paso',
  tableShow: 'Ver tabla equivalente',
  tableHide: 'Ocultar tabla equivalente',
  chartBaseline: 'Barras con origen en cero.',
  chartTableOnly: 'Esta figura se lee en su tabla equivalente.',
  chartAutoScale: 'Eje ajustado al rango de los datos: no parte de cero.',
  scatterAxes: (x: string, y: string) => `Horizontal: ${x}. Vertical: ${y}.`,
  targetLabel: 'Meta',
  targetReached: 'Cumplida',
  targetMissed: 'Bajo la meta',
  previousLabel: 'Período anterior',
  familyLabel: {
    bar: 'Comparación', bar_grouped: 'Comparación', bar_stacked: 'Composición', line: 'Tendencia', pie: 'Composición', donut: 'Composición',
    scatter: 'Relación', bullet: 'Contra la meta', gauge: 'Contra la meta', waterfall: 'Qué explica el cambio', funnel: 'Conversión',
    heatmap: 'Distribución', waffle: 'Composición', venn_two: 'Coincidencia', upset: 'Coincidencia', stat: 'Cifras del período',
  } as Record<string, string>,
  provenanceUnit: 'Unidad',
  provenanceSource: 'Fuente',
  observed: 'Medido',
  estimated: 'Estimado',
  absent: 'Sin dato',
  absentReason: 'La fuente no entrega este dato para el período.',
  limitsTitle: 'Límites de este capítulo',
  chapterEmpty: 'Este capítulo no tiene cifras en esta edición.',
  planTitle: 'Plan de acción',
  planLead: 'Cada acción apunta a una métrica que se leerá en el próximo informe.',
  actionsTitle: 'Acciones',
  methodologyTitle: 'Metodología y referencias',
  methodologyHeading: 'De dónde sale cada cifra',
  editionLimits: 'Límites de la edición',
  references: 'Referencias',
  downloadsTitle: 'Descargas',
  downloadLabel: { report_pdf: 'Informe completo', deck_pdf: 'Presentación', web: 'Versión web' } as Record<string, string>,
  downloadFormat: { report_pdf: 'PDF A4', deck_pdf: 'PDF 16:9', web: '' } as Record<string, string>,
  downloadCta: 'Descargar PDF',
  downloadUnavailable: 'No disponible en esta edición',
  linkNotice: 'Este enlace es personal y puede revocarse.',
  linkExpires: (date: string) => `Vence el ${date}.`,
  confidential: (org: string, code: string, version: number) =>
    `Efeonce Group SpA · Documento confidencial para uso exclusivo de ${org} · Edición ${code}${version > 1 ? `, versión ${version}` : ''}.`,
  states: {
    not_found: { eyebrow: 'Enlace no encontrado', title: 'Este enlace no existe o expiró.', body: 'Pide un enlace nuevo a quien te lo compartió.' },
    gone: { eyebrow: 'Informe retirado', title: 'Este informe fue retirado.', body: 'Si necesitas una versión vigente, pídela a tu contacto en Efeonce.' },
    rate_limited: { eyebrow: 'Demasiadas lecturas', title: 'Demasiadas lecturas en poco tiempo.', body: 'Intenta de nuevo en unos minutos.' },
    error: { eyebrow: 'No pudimos cargarlo', title: 'No pudimos cargar el informe.', body: 'Intenta de nuevo en unos minutos.' },
  },
  contactCta: 'Escribir a Efeonce',
  // Muestra pública para clientes (`/insights/muestra`).
  sampleTitle: 'Muestra · Efeonce Insights',
  sampleDescription: 'Así se ve un informe de Efeonce Insights: la respuesta del mes, la evidencia detrás de cada cifra y el plan para la próxima reunión.',
  sampleChip: 'Muestra con datos de ejemplo',
  sampleOrg: 'Marca de ejemplo',
  sampleNotice: 'Muestra de Efeonce Insights con datos de ejemplo: las cifras no corresponden a ninguna marca real.',
  sampleCtaTitle: '¿Quieres este informe con tus datos?',
  sampleCtaBody: 'Lo armamos cada mes con tu SEO, tus respuestas de IA y tu entrega creativa, con la misma evidencia detrás de cada cifra que ves acá.',
  sampleCtaButton: 'Conversemos',
  // Dirección A — tablero de respuestas
  linkActive: 'Enlace vigente',
  expiresShort: (date: string) => `vence el ${date}`,
  dataAsOf: (date: string) => `datos al ${date}`,
  filterAll: 'Todo',
  filterPlan: 'Plan',
  filtersLabel: 'Filtrar el informe por módulo',
  findingsTitle: 'Lo esencial del mes',
  findingsLead: 'Toca un hallazgo para ver su evidencia.',
  findingOpen: 'Ver evidencia',
  findingClose: 'Cerrar',
  copyLink: 'Copiar enlace',
  copyFindingLink: 'Copiar enlace a este hallazgo',
  linkCopied: 'Enlace copiado',
  viewChart: 'Gráfico',
  viewTable: 'Tabla',
  viewSwitch: 'Cambiar entre gráfico y tabla',
  noEvidenceChart: 'Este hallazgo no tiene una figura propia en esta edición.',
  sceneEyebrow: (module: string) => module,
  howMeasured: 'Cómo se midió',
  howMeasuredLead: 'Fuentes, cortes y límites de cada cifra.',
  downloadShort: 'Descargar',
  backToTop: 'Volver arriba',
  measurementTitle: 'Cómo lo mediremos',
  askTitle: 'Qué necesitamos de ustedes',
  funnelRate: (rate: string) => `pasa el ${rate}`,
  clientLogoAlt: (org: string) => `Logo de ${org}`,
  statusLabel: 'Estado del enlace',
  dockLabel: 'Acciones del informe',
  ogDescription: 'Un informe de Efeonce Insights compartido contigo.',
  present: 'Presentar',
  presentLabel: 'Modo presentación',
  presentExit: 'Salir de la presentación',
  presentNext: 'Siguiente',
  presentPrev: 'Anterior',
  presentCounter: (current: number | string, total: number | string) => `${current} de ${total}`,
  presentHint: 'Flechas para avanzar · Esc para salir',
  groupDetail: 'Detalle',
  // Tarjeta de cifra (modelo 1.4, TASK-1975). Las cifras, la variación y el período vienen escritos en el modelo.
  statEyebrow: 'Cifras del período',
  statCount: (count: number) => (count === 1 ? '1 cifra' : `${count} cifras`),
  statUnitEach: 'cada cifra en la suya',
  /** Frase completa de la variación para lector de pantalla («baja 17,0 %, vs 16.390 en agosto de 2026; empeora»). */
  statChangeSentence: (direction: 'up' | 'down' | 'flat', change: string, versus: string | undefined, tone: 'better' | 'worse' | 'neutral') =>
    `${direction === 'up' ? `sube ${change}` : direction === 'down' ? `baja ${change}` : `sin cambio (${change})`}${versus ? `, ${versus}` : ''}${tone === 'better' ? '; mejora' : tone === 'worse' ? '; empeora' : ''}`,
  waffleUnitNote: (total: string | null) => (total ? `Cada cuadro es una unidad; el total es ${total}.` : 'Cada cuadro es una unidad.'),
}

export type InsightsCopy = typeof INSIGHTS_COPY

export const INSIGHTS_COPY_EN: InsightsCopy = {
  skipLink: 'Skip to content',
  brandEyebrow: 'An Efeonce reading',
  preparedFor: 'Prepared for',
  period: 'Period',
  edition: 'Edition',
  editionValue: (code: string, version: number) => `${code} · version ${version}`,
  asOf: 'Data as of',
  scopeTitle: 'What this report measures',
  periodPartial: 'Open period: the source has not closed this period yet.',
  periodPartialDetail: 'Figures are as of the stated cut-off and do not update on their own.',
  indexTitle: 'Contents',
  indexToggle: 'Report contents',
  indexSections: (count: number) => `${count} sections`,
  progressLabel: (current: number, total: number) => `Section ${current} of ${total}`,
  summaryTitle: 'Executive summary',
  essentialsTitle: 'The essentials this month',
  decisionTitle: 'To decide in the meeting',
  decisionFooter: 'Efeonce recommendation',
  chapterEyebrow: (index: number) => `Chapter ${String(index).padStart(2, '0')}`,
  meaningTitle: 'What it means',
  nextStepTitle: 'Next step',
  tableShow: 'Show data table',
  tableHide: 'Hide data table',
  chartBaseline: 'Bars start at zero.',
  chartTableOnly: 'This figure is read in its data table.',
  chartAutoScale: 'Axis fitted to the data range: it does not start at zero.',
  scatterAxes: (x: string, y: string) => `Horizontal: ${x}. Vertical: ${y}.`,
  targetLabel: 'Target',
  targetReached: 'Met',
  targetMissed: 'Below target',
  previousLabel: 'Previous period',
  familyLabel: {
    bar: 'Comparison', bar_grouped: 'Comparison', bar_stacked: 'Composition', line: 'Trend', pie: 'Composition', donut: 'Composition',
    scatter: 'Relationship', bullet: 'Against target', gauge: 'Against target', waterfall: 'What drove the change', funnel: 'Conversion',
    heatmap: 'Distribution', waffle: 'Composition', venn_two: 'Overlap', upset: 'Overlap', stat: 'Figures for the period',
  },
  provenanceUnit: 'Unit',
  provenanceSource: 'Source',
  observed: 'Measured',
  estimated: 'Estimated',
  absent: 'No data',
  absentReason: 'The source does not provide this figure for the period.',
  limitsTitle: 'Limits of this chapter',
  chapterEmpty: 'This chapter has no figures in this edition.',
  planTitle: 'Action plan',
  planLead: 'Each action points to a metric we will read in the next report.',
  actionsTitle: 'Actions',
  methodologyTitle: 'Methodology and references',
  methodologyHeading: 'Where each figure comes from',
  editionLimits: 'Limits of this edition',
  references: 'References',
  downloadsTitle: 'Downloads',
  downloadLabel: { report_pdf: 'Full report', deck_pdf: 'Presentation', web: 'Web version' },
  downloadFormat: { report_pdf: 'A4 PDF', deck_pdf: '16:9 PDF', web: '' },
  downloadCta: 'Download PDF',
  downloadUnavailable: 'Not available in this edition',
  linkNotice: 'This link is personal and can be revoked.',
  linkExpires: (date: string) => `It expires on ${date}.`,
  confidential: (org: string, code: string, version: number) =>
    `Efeonce Group SpA · Confidential document for the exclusive use of ${org} · Edition ${code}${version > 1 ? `, version ${version}` : ''}.`,
  states: {
    not_found: { eyebrow: 'Link not found', title: 'This link does not exist or has expired.', body: 'Ask whoever shared it with you for a new link.' },
    gone: { eyebrow: 'Report withdrawn', title: 'This report was withdrawn.', body: 'If you need a current version, ask your Efeonce contact.' },
    rate_limited: { eyebrow: 'Too many reads', title: 'Too many reads in a short time.', body: 'Try again in a few minutes.' },
    error: { eyebrow: 'We could not load it', title: 'We could not load the report.', body: 'Try again in a few minutes.' },
  },
  contactCta: 'Write to Efeonce',
  sampleTitle: 'Sample · Efeonce Insights',
  sampleDescription: 'This is what an Efeonce Insights report looks like: the answer of the month, the evidence behind every figure and the plan for the next meeting.',
  sampleChip: 'Sample with example data',
  sampleOrg: 'Example brand',
  sampleNotice: 'Efeonce Insights sample with example data: the figures do not belong to any real brand.',
  sampleCtaTitle: 'Want this report with your data?',
  sampleCtaBody: 'We build it every month from your SEO, your AI answers and your creative delivery, with the same evidence behind every figure you see here.',
  sampleCtaButton: "Let's talk",
  linkActive: 'Link active',
  expiresShort: (date: string) => `expires ${date}`,
  dataAsOf: (date: string) => `data as of ${date}`,
  filterAll: 'All',
  filterPlan: 'Plan',
  filtersLabel: 'Filter the report by module',
  findingsTitle: 'The essentials this month',
  findingsLead: 'Tap a finding to see its evidence.',
  findingOpen: 'See evidence',
  findingClose: 'Close',
  copyLink: 'Copy link',
  copyFindingLink: 'Copy link to this finding',
  linkCopied: 'Link copied',
  viewChart: 'Chart',
  viewTable: 'Table',
  viewSwitch: 'Switch between chart and table',
  noEvidenceChart: 'This finding has no figure of its own in this edition.',
  sceneEyebrow: (module: string) => module,
  howMeasured: 'How it was measured',
  howMeasuredLead: 'Sources, cut-offs and limits of each figure.',
  downloadShort: 'Download',
  backToTop: 'Back to top',
  measurementTitle: 'How we will measure it',
  askTitle: 'What we need from you',
  funnelRate: (rate: string) => `${rate} move on`,
  clientLogoAlt: (org: string) => `${org} logo`,
  statusLabel: 'Link status',
  dockLabel: 'Report actions',
  ogDescription: 'An Efeonce Insights report shared with you.',
  present: 'Present',
  presentLabel: 'Presentation mode',
  presentExit: 'Exit presentation',
  presentNext: 'Next',
  presentPrev: 'Previous',
  presentCounter: (current: number | string, total: number | string) => `${current} of ${total}`,
  presentHint: 'Arrows to move · Esc to exit',
  groupDetail: 'Detail',
  statEyebrow: 'Figures for the period',
  statCount: (count: number) => (count === 1 ? '1 figure' : `${count} figures`),
  statUnitEach: 'each figure in its own',
  statChangeSentence: (direction: 'up' | 'down' | 'flat', change: string, versus: string | undefined, tone: 'better' | 'worse' | 'neutral') =>
    `${direction === 'up' ? `up ${change}` : direction === 'down' ? `down ${change}` : `no change (${change})`}${versus ? `, ${versus}` : ''}${tone === 'better' ? '; better' : tone === 'worse' ? '; worse' : ''}`,
  waffleUnitNote: (total: string | null) => (total ? `Each square is one unit; the total is ${total}.` : 'Each square is one unit.'),
}

/** Diccionario del chrome según el idioma de la edición (por defecto, es-CL). */
export const getInsightsCopy = (locale: string | null | undefined): InsightsCopy =>
  locale?.toLowerCase().startsWith('en') ? INSIGHTS_COPY_EN : INSIGHTS_COPY
