export const xrayCopy = {
  name: 'AEO X-Ray', disclaimer: 'Muestra de trabajo de Efeonce',
  disclaimerBody: 'Propuesta ilustrativa. No es una publicación ni un canal del banco.',
  read: 'Leer la pieza', explore: 'Explorar la radiografía',
  landing: 'Landing page', article: 'Artículo de blog',
  prepared: 'Preparado para', index: 'En esta guía',
  inspect: 'Explorar este bloque', technical: 'La capa técnica',
  inspectorTitle: 'Las decisiones detrás de la pieza',
  inspectorIntro: 'Qué resuelve cada decisión, dónde se aplica y qué falta verificar.',
  all: 'Ver toda la capa', close: 'Cerrar exploración',
  sources: 'Fuentes y condiciones', sourceDate: 'Consultado el',
  schema: 'Datos estructurados propuestos',
  schemaNote: 'Se muestran como texto. La muestra no publica estos datos en nombre del banco.',
  page: 'En la página', site: 'En el sitio', block: 'En este bloque',
  scope: 'Ámbito', category: 'Especialidad', evidence: 'Evidencia',
  by: 'Por', review: 'Revisión del banco pendiente',
  sourceLink: 'Consultar fuente', next: 'Continúa con',
  categories: { technical: 'SEO técnico', 'on-page': 'SEO on-page', aeo: 'AEO', conversion: 'Conversión' },
  statuses: { proposed: 'Propuesto', implemented: 'Implementado en la muestra', verified: 'Verificado', measured: 'Medido' },
  value: {
    summary: 'El valor detrás de la pieza', questions: 'preguntas', open: 'Explorar decisiones',
    eyebrow: 'De la intención a la decisión', title: 'Una pregunta. Una respuesta que se puede comprobar.',
    intro: 'Explora cómo conectamos una necesidad de búsqueda con contenido útil, decisiones técnicas y un siguiente paso.',
    choose: 'Preguntas resueltas por la pieza', answer: 'Contenido real de esta muestra', why: 'La decisión SEO / AEO',
    sources: 'Fuentes de esta respuesta', inspect: 'Ver el bloque en la radiografía', read: 'Ir a la respuesta',
    measureTitle: 'Cómo comprobaríamos el valor después de publicar',
    measureIntro: 'Estas son las señales que contrastaríamos con una línea base. Esta muestra demuestra la implementación; todavía no mide rendimiento del banco.',
    measure: [
      {label:'SEO · descubrimiento',question:'¿Nos encuentran por las consultas que queremos resolver?',method:'Comparar impresiones, clics y CTR por consulta y página en Search Console, con país, dispositivo y períodos equivalentes. Comprobar indexación y rendimiento de campo por separado.'},
      {label:'AEO · presencia y exactitud',question:'¿Qué motores usan la fuente y con qué precisión?',method:'Repetir un panel definido de preguntas por motor, modo y fecha. Registrar mención de marca, URL citada y exactitud de tasas, moneda y condiciones. Tener la respuesta en la página no demuestra una cita.'},
      {label:'Conversión · siguiente paso',question:'¿La respuesta ayuda a avanzar hacia el producto?',method:'Medir lectura, clic en el CTA y llegada al canal oficial. Conectar aperturas o fondeo únicamente con datos y acceso autorizados del banco; una visita o una cita no equivale a una cuenta abierta.'},
    ],
  },
  states: {
    not_found: { title: 'Este enlace no está disponible', body: 'Solicita un enlace vigente a tu contacto de Efeonce.' },
    gone: { title: 'Este enlace dejó de estar disponible', body: 'La muestra fue retirada o el acceso fue revocado. Tu contacto de Efeonce puede ayudarte.' },
    rate_limited: { title: 'Espera un momento', body: 'Recibimos varias solicitudes. Vuelve a intentarlo en unos instantes.' },
    error: { title: 'No pudimos cargar la muestra', body: 'Intenta de nuevo en unos instantes. Si continúa, contacta a Efeonce.' },
  },
} as const
