export const xrayCopy = {
  name: 'AEO X-Ray', disclaimer: 'Muestra de trabajo de Efeonce',
  disclaimerBody: 'Propuesta ilustrativa. No es una publicación ni un canal del banco.',
  read: 'Leer la pieza', explore: 'Explorar la radiografía',
  landing: 'Landing page', article: 'Artículo de blog',
  prepared: 'Preparado para', index: 'En esta guía',
  inspect: 'Explorar este bloque', technical: 'La capa técnica',
  inspectorTitle: 'Las decisiones detrás de la pieza',
  inspectorIntro: 'Qué resuelve cada decisión, dónde se aplica y qué falta verificar.',
  all: 'Ver toda la capa', close: 'Cerrar exploración',
  sources: 'Fuentes y condiciones', sourceDate: 'Consultado el',
  schema: 'Datos estructurados propuestos',
  schemaNote: 'Se muestran como texto. La muestra no publica estos datos en nombre del banco.',
  page: 'En la página', site: 'En el sitio', block: 'En este bloque',
  scope: 'Ámbito', category: 'Especialidad', evidence: 'Evidencia',
  by: 'Por', review: 'Revisión del banco pendiente',
  sourceLink: 'Consultar fuente', next: 'Continúa con',
  categories: { technical: 'SEO técnico', 'on-page': 'SEO on-page', aeo: 'AEO', conversion: 'Conversión' },
  statuses: { proposed: 'Propuesto', implemented: 'Implementado en la muestra', verified: 'Verificado', measured: 'Medido' },
  states: {
    not_found: { title: 'Este enlace no está disponible', body: 'Solicita un enlace vigente a tu contacto de Efeonce.' },
    gone: { title: 'Este enlace dejó de estar disponible', body: 'La muestra fue retirada o el acceso fue revocado. Tu contacto de Efeonce puede ayudarte.' },
    rate_limited: { title: 'Espera un momento', body: 'Recibimos varias solicitudes. Vuelve a intentarlo en unos instantes.' },
    error: { title: 'No pudimos cargar la muestra', body: 'Intenta de nuevo en unos instantes. Si continúa, contacta a Efeonce.' },
  },
} as const
